// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import NavbarWrapper from "./components/NavbarWrapper"; // NEW wrapper for client hooks
import "../styles/footer.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dr. Ouafae Elmehraoui - Endocrinologie & Diabétologie",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen relative`}
      >
        <video
          autoPlay
          loop
          muted
          playsInline
          className="fixed top-0 left-0 w-full h-full object-cover -z-50"
        >
          <source src="/bg.mp4" type="video/mp4" />
        </video>
          <NavbarWrapper /> {/* Client wrapper */}

        <div className="relative z-10">
          <main className="w-full">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
