// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import NavbarWrapper from "./components/NavbarWrapper";
import LoadingOverlay from "./components/LoadingOverlay"; // ← Ajoute ceci
import "../styles/footer.css";
import connectDB from "./lib/mongoose"; // 👈 AJOUTE ÇA

connectDB(); // 🔥 pré-connexion MongoDB (sans await)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport = {
  width: "device-width",
  initialScale: 1,
};

export const metadata = {
  title: "Dr. Ouafae Elmehraoui - Endocrinologie & Diabétologie",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen relative`}
      >
        <LoadingOverlay /> {/* ← Ajoute le loader ici */}
        <NavbarWrapper />

        <div className="relative z-10">
          <main className="w-full">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}